export const NavbarHamburger = () => {
  return (
    <div className="text-base items-center bg-white box-border caret-transparent gap-x-1 flex flex-col shrink-0 h-10 justify-center leading-4 min-h-[auto] min-w-[auto] gap-y-1 w-10 overflow-hidden rounded-bl rounded-br rounded-tl rounded-tr md:text-xl md:[align-items:normal] md:bg-transparent md:gap-x-[normal] md:hidden md:flex-row md:shrink md:h-auto md:justify-normal md:leading-5 md:min-h-0 md:min-w-0 md:gap-y-[normal] md:w-auto md:overflow-visible md:rounded-none hover:text-black hover:bg-neutral-100 hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-bl hover:rounded-br hover:rounded-tl hover:rounded-tr hover:border-0 hover:border-none hover:border-black">
      <div className="text-base bg-black box-border caret-transparent h-0.5 leading-4 min-h-[auto] min-w-[auto] w-4 md:text-xl md:bg-transparent md:h-auto md:leading-5 md:min-h-0 md:min-w-0 md:w-auto hover:text-black hover:bg-neutral-900 hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-none hover:border-0 hover:border-none hover:border-black"></div>
      <div className="text-base bg-black box-border caret-transparent h-0.5 leading-4 min-h-[auto] min-w-[auto] w-4 md:text-xl md:bg-transparent md:h-auto md:leading-5 md:min-h-0 md:min-w-0 md:w-auto hover:text-black hover:bg-neutral-900 hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-none hover:border-0 hover:border-none hover:border-black"></div>
      <div className="text-base bg-black box-border caret-transparent h-0.5 leading-4 min-h-[auto] min-w-[auto] w-4 md:text-xl md:bg-transparent md:h-auto md:leading-5 md:min-h-0 md:min-w-0 md:w-auto hover:text-black hover:bg-neutral-900 hover:shadow-none hover:outline-offset-0 hover:outline-0 hover:no-underline hover:decoration-solid hover:decoration-auto hover:rounded-none hover:border-0 hover:border-none hover:border-black"></div>
    </div>
  );
};
